cc_library(
    name="merge_arrays",
    srcs=["merge_arrays.cpp"],
)

cc_library(
    name="remove_element",
    srcs=["remove_element.cpp"],
)

cc_library(
    name="add_two_numbers",
    srcs=["add_two_numbers.cpp"],
)
