name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install tools
        run: |
          ./set-me-up.py --skip_prompt

      - name: Pre-commit checks
        run: uv run pre-commit run --all-files

      - name: Run tests
        run: uv run pytest --verbose ./src/python/
