name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install MkDocs + Material
        run: pip install mkdocs>=1.6.1 mkdocs-material>=9.6.16

      - name: Deploy with MkDocs
        run: mkdocs gh-deploy --force
