name: Rebase
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Rebase
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.REBASE_PAT }}
          commands: rebase
          permission: write
          issue-type: pull-request